sudo: false  # Now the build will be running on the new container based platform

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - "pypy3"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      - build-essential

install:
 - pip install --upgrade pip
 - pip install --install-option="--no-cython-compile" Cython 
 - pip install .

script:
 - cd `mktemp -d`  # Navigate into a temporary directory to avoid loading the local code
 - nosetests --verbosity=2 nxmetis.tests.test_metis

notifications:
  email: false
